Artist.create({name: "Prince"})
Artist.create({name: "Bob Dylan"})
Album.create({artist_id: 2, title: "Blood on the Tracks"})
Album.create({artist_id: 2, title: "Highway 61"})
Album.create({artist_id: 1, title: "Purple Rain"})
